config/routes.rb
Rails.application.routes.draw do

  get '/map_locations' => 'welcome#map_locations'
  get '/search' => 'welcome#search'
  resources :ratings do
    get 'get_rating'
    get 'rating_update'
  end

  get 'users/index'

  get 'users/show'

  post 'users/update'

  #generates /events/get_events route for calendar
  resources :events do
    get :get_events, on: :collection
  end

  resources :rsvps
  resources :event_reviews
  resources :venue_reviews
  resources :comments

  resources :events do
    get 'rating_update'
    get :add_featured
    get :remove_featured
  end
  resources :venues do
    # map locations for ...
    member do
      get 'map_location'
    end
    # Retrieve all map location for all venues
    # collection do
    #   get 'map_locations'
    # end
  end

  # Devise routes
  devise_for :users, path_prefix: 'my', controllers: { registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root to: "welcome#index"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :venues
  has_many :venue_reviews
  has_many :event_reviews
  has_many :comments
  has_many :ratings
  has_many :events, through: :rsvp

  # resourcify

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true

  validates :first_name, :last_name, presence: true

  has_attached_file :image, styles: { small: "64x64#", med: "100x100#", large: "350x275#", xlarge: "400x400#" }, :default_url => "profile_:style.jpeg"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Only allow letter, number, underscore and punctuation.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]
  devise :omniauthable, omniauth_providers: [:facebook, :twitter]

  after_save :assign_role

  def assign_role
    add_role(:default)
  end

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end 

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login


  def self.from_omniauth(auth)
    if auth.provider == "facebook"
      # was where(provider: auth.provider, uid: auth.uid).first_or_create do |user|)
      where(email: auth.info.email).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
          # Helper methods to split info coming in into username, first_name, last_name etc.
          name_array = auth.info.name.split(" ")
          email_array = auth.info.email.split("@")
        user.username = email_array[0]
          # auth.info.name.gsub(/\s+/, "")   # assuming the user model has a name
        user.first_name = name_array[0]
        user.last_name = name_array[1]
        user.image = URI.parse(auth.info.image) # assuming the user model has an image


        # uri = URI.parse(auth.info.image) if auth.info.image?
        # uri.scheme = 'https'
        # user.image = uri
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        # user.skip_confirmation!
      end
    else
      # Was where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      where(username: auth.info.nickname).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        #if the email is not find from twitter, add in the user id as the twitter email.
        user.email = auth.info.email || "#{auth.uid}@twitter.com"
        user.password = Devise.friendly_token[0,20]
        user.username = auth.info.nickname
        name_array = auth.info.name.split(" ")
        user.first_name = name_array[0]
        user.last_name = name_array[1]
        user.image = auth.info.image
     end
    end
  end


  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = lower(:value)", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        conditions[:email].downcase! if conditions[:email]
        where(conditions.to_h).first
      end
    end
  #  def self.new_with_session(params, session)
  #     super.tap do |user|
  #       if data = session["devise.twitter_data"] && session["devise.twitter_data"]["extra"]["raw_info"]
  #         user.email = data["email"] if user.email.blank?
  #       end
  #     end
  #   end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    @user.save

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # DELETE /resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
    @ability = Ability.new(current_user)
  end

  def show
    @user = User.find(params[:id])
    @user_events = Event.where(user_id: params[:id])
    @user_venues = Venue.where(user_id: params[:id])
    @user_rsvps = Rsvp.where(user_id: params[:id])
    @ability = Ability.new(current_user)
  end

  def edit
    @user = User.find(params[:id])
    @ability = Ability.new(current_user)
  end

  def update
    @user = User.find(params[:id])
    @ability = Ability.new(current_user)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_index_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.soft_delete

    respond_to do |format|
      format.html { redirect_to users_index_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :first_name, :last_name, :street_1, :street_2, :city, :state, :zip, :image)
    end

end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit</h2>

<%= form_for(@user, html: { method: :put, multipart: true }) do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :street_1 %>
    <%= f.text_field :street_1, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :street_2 %>
    <%= f.text_field :street_2, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image  %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <!-- <div class="form-group">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="form-group">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div> -->

  <div class="actions form-group">
    <%= f.submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

<% if @ability.can?(:manage, @user, id: @user.id) %>
  <h3>Cancel my account</h3>

  <p>Unhappy? <%= button_to "Cancel my account", user_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></p>
<% else %>
  <h3>Cancel this user's account</h3>

  <p>Do you want to cancel this user's account? <%= button_to "Yes", user_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></p>
<% end %>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<table class="table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>

        <td><%= link_to 'Show', user %></td>
        <!-- Note: The way this works is that this condition works on whoever current_user is, regardless of the fact that current_user may be an admin. Because in an if-else condition the first condition that is true is ALWAYS the condition that is chosen, keep ownership in mind if you change the conditions. -->
        <% if @ability.can?(:manage, user, id: current_user.id) %>
          <!-- if a user didn't create an account with omniauth, they will use the Devise edit page, otherwise they'll use users edit page -->
          <% if user.provider.nil? %>
            <td><%= link_to 'Edit', edit_user_registration_path %></td>
          <% else %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <% end %>
          <td><%= link_to 'Destroy', user_path(user), data: { confirm: "Are you sure?" }, method: :delete %></td>
        <% elsif @ability.can?(:rud, user) %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user_path(user), data: { confirm: "Are you sure?" }, method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
    <h1>Hi, <%= @user.username %>!</h1>


    <p>
      <strong>Username:</strong>
      <%= @user.username %>
    </p>

    <% if @user.image.file? %>
    <p>
     <a><%= image_tag(@user.image.url(:large)) %></a>
     <% else %>
     <%= link_to image_tag('profile_large.jpeg') %>
    </p>
    <% end %>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if !@user.street_1.nil? && !@user.street_1.empty? %>
  <p>
  <strong>Street 1:</strong>
    <%= @user.street_1 %>
  </p>
<% end %>

<% if !@user.street_2.nil? && !@user.street_2.empty? %>
  <p>
  <strong>Street 2:</strong>
    <%= @user.street_2 %>
  </p>
<% end %>

<% if !@user.city.nil? && !@user.city.empty? %>
  <p>
  <strong>City:</strong>
    <%= @user.city %>
  </p>
<% end %>

<% if !@user.state.nil? && !@user.state.empty? %>
  <p>
  <strong>State:</strong>
    <%= @user.state %>
  </p>
<% end %>

<% if !@user.zip.nil? && !@user.zip.empty? %>
  <p>
  <strong>Zip:</strong>
    <%= @user.zip %>
  </p>
<% end %>

<% if @ability.can?(:manage, @user, id: @user.id) %>
  <!-- if a user didn't create an account with omniauth, they will use the Devise edit page, otherwise they'll use users edit page -->
  <% if @user.provider.nil? %>
    <%= button_to "Edit My Profile", edit_user_registration_path, method: "get", class: "btn btn-info" %>
  <% else %>
    <%= button_to 'Edit My Profile', edit_user_path(@user), method: "get", class: "btn btn-info"  %>
  <% end %>
<% elsif @ability.can?(:rud, @user) %>
  <%= button_to 'Edit My Profile', edit_user_path(@user), method: "get", class: "btn btn-info"  %>
<% end %>

<br>

<h4>My Venues:</h4>
<% if !@user_venues.nil? && !@user_venues.empty? %>
<table>
  <% @user_venues.each do |venue| %>
  <tr>
    <td><a href="/venues/<%= venue.id %>"><%= venue.name %></a></td>
  </tr>
  <% end %>
</table>
<% else %>
<%= link_to 'Add a new venue', new_venue_path %>
<% end %>

  <h4>My Events</h4>
  <% if !@user_events.nil? && !@user_events.empty? %>
  <table>
    <% @user_events.each do |event| %>
      <tr>
        <td><a href="/events/<%= event.id %>"><%= event.name %></a></td>
      </tr>
    <% end %>
  </table>
  <% else %>
    <%= link_to 'Create a new event', new_event_path %>
<% end %>

  <h4>My RSVPs:</h4>
  <% if !@user_rsvps.nil? && !@user_rsvps.empty? %>
  <table>
    <% @user_rsvps.each do |rsvp| %>
      <tr>
        <td><a href="/events/<%= rsvp.event_id %>"><%= rsvp.event.name %></a></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <%= link_to 'RSVP to some events', events_path %>
<% end %>