config/routes.rb
Rails.application.routes.draw do

  get '/map_locations' => 'welcome#map_locations'
  get '/search' => 'welcome#search'
  resources :ratings do
    get 'get_rating'
    get 'rating_update'
  end

  get 'users/index'

  get 'users/show'

  post 'users/update'

  #generates /events/get_events route for calendar
  resources :events do
    get :get_events, on: :collection
  end

  resources :rsvps
  resources :event_reviews
  resources :venue_reviews
  resources :comments

  resources :events do
    get 'rating_update'
    get :add_featured
    get :remove_featured
  end
  resources :venues do
    # map locations for ...
    member do
      get 'map_location'
    end
    # Retrieve all map location for all venues
    # collection do
    #   get 'map_locations'
    # end
  end

  # Devise routes
  devise_for :users, path_prefix: 'my', controllers: { registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root to: "welcome#index"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :user, presence: true

  belongs_to :venue
  validates :venue, presence: true

  has_many :event_reviews
  has_many :comments
  has_many :users, through: :rsvp
  has_many :ratings, :dependent => :delete_all

  validates :name, presence: true

#Adding paperclip
  has_attached_file :image, styles: { small: "64x64#", med: "100x100#", large: "350x275#", xlarge: "400x400#" }, :default_url => "default_:style.png"
  validates_attachment :image,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }

    # instead of deleting, indicate the user requested a delete & timestamp it
    def soft_delete
      update_attribute(:deleted_at, Time.current)
    end

    # check if event is active or has been soft deleted
    def active?
      !deleted_at
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout "index-show", only: [:show, :index]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/events', :alert => exception.message
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @ability = Ability.new(current_user)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    if @event.active?
      # Set ability
      @ability = Ability.new(current_user)

      # Event review
      @event_review = EventReview.new
      @event_reviews = EventReview.where(event_id: @event.id)

      # Set up blank comment and list of comments
      @comment = Comment.new
      @comments = Comment.where(event_id: @event.id)

      # Finds user's current rating if existing or creates new blank rating. Also finds rating average
      rating = Rating.where(user: current_user, event: @event)
      if rating.length >= 1
        @rating = rating[0]
      else
        @rating = Rating.new
      end

      # RSVP
      if user_signed_in?
        @remove_rsvp = Rsvp.find_by(event_id: params[:id], user_id: current_user.id)
      end
    else
      redirect_to '/events'
    end
  end

  # GET /events/new
  def new
    @venues_for_select = Venue.all.map do |venue|
      [venue.name, venue.id]
    end
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    if @event.active?
      # Set ability
      @ability = Ability.new(current_user)

      if !current_user.nil? && @ability.can(:manage, @event, user_id: current_user.id)
        @event = Event.find(params[:id])
        @venues_for_select = Venue.all.map do |venue|
          [venue.name, venue.id]
        end
      else
        redirect_to 'events'
      end
    else
      redirect_to '/events'
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html {
          @venues_for_select = Venue.all.map do |venue|
            [venue.name, venue.id]
          end
          render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @ability = Ability.new(current_user)
    if !@ability.can(:manage, @event, user_id: current_user.id)
      redirect_to 'events'
    end
    # Note: the following lines not needed, because now we do soft delete
    # @event.ratings.delete_all
    # Rsvp.where(event_id: @event.id).delete_all
    @event.soft_delete
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_events
    @events = Event.all
    events_array = []
    @events.each do |event|
      events_array << { id: event.id, title: event.name, start: event.date, url: Rails.application.routes.url_helpers.event_path(event.id) }
    end
    render :json => events_array.to_json
  end

  def add_featured
    @event = Event.find(params[:event_id])
    featured = Event.where(:featured => true)
    if featured.count > 2
      flash[:alert] = "Three (3) events are already featured, remove one before adding another. Current Featured Events: (1) #{featured[0].name}, (2) #{featured[1].name}, (3) #{featured[2].name}"

      redirect_to "/events/#{@event.id}"
    else
      @event.featured = true
      @event.save
      redirect_to "/events/#{@event.id}"
    end
  end

  def remove_featured
    @event = Event.find(params[:event_id])
    @event.featured = false
    @event.save
    redirect_to "/events/#{@event.id}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :venue_id, :description, :user_id, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.datetime_select :date, { order: [:month, :day, :year], ampm: true, :minute_step => 15 } %>
  </div>

  <div class="form-group">
    <%= f.label :venue_id %>
    <%= select(:event, :venue_id, @venues_for_select, { class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 10 %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <% ability = Ability.new(current_user) %>
  <% if ability.can?(:create, Event) %>
    <div class="form-group">
      <input type="hidden" value="<%= current_user.id %>" name="event[user_id]">
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Submit Event', class: "btn btn-success"  %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-12" id="banner">
    <h1>Events</h1>
  </div>
</div>

<div class="row">
  <% @events.each do |event| %>
    <% if event.active? %>
      <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
          <a><%=image_tag(event.image.url(:small)) %></a>
          <div class="caption">
            <h4><%= link_to "#{event.name}", event %></h4>
            <h6><%= upcase_first date_to_s(event.date) %></h6>
            <p><strong>Venue:</strong> <%= link_to "#{event.venue.name}", "/venues/#{event.venue_id}" %></p>
            <p><strong>Description:</strong><br><%= event.description %></p>

            <div id="ratings">
              <p class="pull-right"><strong><%= show_rating event.ratings %></strong></p>
              <p><strong>Avg Rating: <%= format event.ratings.average("rating") %></strong></p>
            </div>
          </div>
          <p>
            <% if !current_user.nil? && event.user == current_user %>
              <%= link_to 'Edit', edit_event_path(event) %> |
              <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if !current_user.nil? && @ability.can?(:create, Event) %>
    <div class="col-sm-4 col-lg-4 col-md-4">
        <h4><%= link_to 'New Event', new_event_path %></h4>
        <p>Planning an exiciting new dogapalooza? Click the button below to get started!</p>
        <a class="btn btn-primary" href="/events/new">Create New Event</a>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% content_for :head do %>
  <meta property="og:url"           content="https://barksandrec.herokuapp.com/events/<%= event_path(@event) %>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="<%= @event.name %>" />
  <meta property="og:description"   content="<%= @event.description %>" />
  <meta property="og:image"         content="<%= @event.image %>" />
<% end %>

<!-- Bootstrap Template -->
<div class="thumbnail">
  <div id="event_map" data-venue-id="<%=@event.venue.id%>">
    Google Map will appear here...
  </div>

  <div class="caption-full">
    <div id="info-left">
      <div id="info-text">
        <p>
          <h3><%= @event.name %></h3>
          <p>
            <% if !current_user.nil? && @ability.can?(:rud, @event, user_id: current_user.id) %>
              <% if current_user.has_role?(:admin) %>
                <% if !@event.featured %>
                <%= link_to 'Make Featured', "#{event_path(@event)}/add_featured" %> |
                <% else %>
                  <%= link_to 'Remove Featured', "#{event_path(@event)}/remove_featured" %> |
                <% end %>
              <% end %>
              <%= link_to 'Edit', edit_event_path(@event) %> |
              <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
        </p>

        <p>
        <!-- Share/Tweet buttons for Facebook and Twitter -->
          <div class="fb-share-button" data-href="https://barksandrec.herokuapp.com/events/<%= event_path(@event) %>" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A3000%2F&amp;src=sdkpreparse">Share</a></div>
          <a href="https://twitter.com/share/tweet?text=Bring%20your%20dogs%20to%20<%= @event.name.gsub!(/\s/,'%20') %>%20as%20found%20on%20WhelpSD.com%21" class="twitter-share-button" data-show-count="false">Tweet</a>
        </p>

        <p>
          <%= upcase_first date_to_s(@event.date) %>
        </p>

        <p>
          <strong>Venue:</strong>
          <%= @event.venue.name %>
        </p>

        <p>
          <strong>Hosted By:</strong>
          <%= link_to "#{@event.user.username}", "/users/#{@event.user_id}"  %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @event.description %>
        </p>
      </div> <!-- info-text -->

      <br>

      <!-- Ratings -->
      <div id="ratings">
        <%= render 'ratings/form', rating: @rating %>

        <% if !current_user.nil? && @ability.can?(:create, Rating) %>
          <p class="pull-left">
            <div id="rating_div">
              <strong>My Rating:</strong>
              <span id="rating_span">
                <%= image_tag("star-off.png", id: "star_1") %>
                <%= image_tag("star-off.png", id: "star_2") %>
                <%= image_tag("star-off.png", id: "star_3") %>
                <%= image_tag("star-off.png", id: "star_4") %>
                <%= image_tag("star-off.png", id: "star_5") %>
              </span>
            </div>
          </p>

        <% elsif current_user.nil? %>
          <p><%= link_to "Sign in to rate this event!", new_user_session_path %></p>
        <% end %>

        <div class="rating_block">
          <span class="pull-left">
            <strong>Average Rating:&nbsp</strong>
            <span id="avg_rating"></span>
          </span>
          <span class="pull-right">
            <span id="count_rating">&nbspRatings</span>
          </span>
        </div> <!-- rating_block div -->
      </div> <!-- End Ratings -->

    </div> <!-- class="info-left" -->

    <div id="info-right">
      <%= image_tag @event.image.url(:large) %>
    </div>

    <div id="rsvp">
      <hr>
      <!-- form for user to rsvp to an event -->
      <% if !current_user.nil? && @ability.can?(:create, Rsvp) && Rsvp.find_by(user_id: current_user.id, event_id: @event.id).nil? %>

        <% if @event.date >= DateTime.now %>
          <%= form_for Rsvp.new, url: rsvps_path, method: :post do |f| %>
            <p><strong>My RSVP:</strong>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :event_id, value: params[:id] %>
              <%= f.submit 'Count Me In', :class => 'btn btn-success' %>
            </p>
          <% end %>
        <% else %>
          <p>Sorry, it's too late to RSVP to this event.</p>
        <% end %>

      <!-- form to delete user rsvp -->
      <% elsif !current_user.nil? && @ability.can?(:create, Rsvp) && !Rsvp.find_by(user_id: current_user.id, event_id: @event.id).nil? %>

        <% if @event.date >= DateTime.now %>
          <%= form_for Rsvp.find_by(user_id: current_user.id, event_id: params[:id]), url: rsvp_path, method: :delete do |f| %>
            <p><strong>My RSVP:</strong>
              <%= f.submit "Cancel RSVP", :class => 'btn btn-danger' %>
            </p>
          <% end %>
        <% else %>
          <p><strong>My RSVP:</strong>
          <button type = "button" class = "btn btn-info">RSVPd</button>
        <% end %>
      <% elsif @event.date >= DateTime.now && current_user.nil? %>
        <p><%= link_to "Sign in to RSVP!", new_user_session_path %></p>
      <% end %>


      <!-- end of form that deletes user's rsvp -->
      <p>
        <strong>RSVPs</strong>
        <% rsvp_length = Rsvp.where(event_id: @event.id).length %>
          <% if rsvp_length == 1 %>
          - (<%= rsvp_length %> attendee)
          <% else %>
             - (<%= rsvp_length %> attendees)
          <% end %>

        <ol>
        <% Rsvp.where(event_id: @event.id).each do |attendee| %>
          <li><%= link_to "#{attendee.user.first_name} #{attendee.user.last_name}", "/users/#{attendee.user.id}" %></li>
        <% end %>
        </ol>
      </p>
    </div> <!-- class="rsvp" -->
  </div> <!-- class="caption-full" -->
</div> <!-- class="thumbnail" -->

<!-- Added some space -->
<div class="five_space">
</div>

<!-- Comments -->
<p class="pull-right"><%= @comments.count %> Comment(s)</p>
<h3>Comments</h3>
<div class="well">
  <div>
    <!-- New comment form renders if user is logged in -->
    <!-- Also displays current user's rating of event -->
    <% if !current_user.nil? %>
      <h3>New Comment</h3>
      <%= render 'comments/form', comment: @comment %>
    <% else %>
     <%= link_to 'Sign in to Comment', new_user_session_path %>
    <% end %>
  </div>

  <hr>
  <% if @comments %>
    <% @comments.each do |comment| %>
      <div class="row">
        <div class="col-md-12">
          <h4> <%= comment.title %> </h4>
          <span>Posted By: <%= link_to "#{comment.user.username}", "/users/#{comment.user_id}" %> </span>
          <span class="pull-right"><%= "Posted " + date_to_s(comment.created_at) %></span>
          <p>
          <%= comment.text %>
          </p>
          <% if current_user == comment.user %>
            <%= link_to 'Edit', edit_comment_path(comment) %> |
            <%= link_to 'Destroy', comment_path(comment), method: "delete" %>
          <% end %>
        </div>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>