config/routes.rb
Rails.application.routes.draw do

  get '/map_locations' => 'welcome#map_locations'
  get '/search' => 'welcome#search'
  resources :ratings do
    get 'get_rating'
    get 'rating_update'
  end

  get 'users/index'

  get 'users/show'

  post 'users/update'

  #generates /events/get_events route for calendar
  resources :events do
    get :get_events, on: :collection
  end

  resources :rsvps
  resources :event_reviews
  resources :venue_reviews
  resources :comments

  resources :events do
    get 'rating_update'
    get :add_featured
    get :remove_featured
  end
  resources :venues do
    # map locations for ...
    member do
      get 'map_location'
    end
    # Retrieve all map location for all venues
    # collection do
    #   get 'map_locations'
    # end
  end

  # Devise routes
  devise_for :users, path_prefix: 'my', controllers: { registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root to: "welcome#index"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  validates :user, presence: true

  belongs_to :venue, optional: true
  belongs_to :event, optional: true

  validates :rating, presence: true, inclusion: { in: 1..5}

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # Return rating as JSON for given rating ID
  def get_rating
    # If rating for given user + event exists then return that value. Otherwise return a value of 0.
    type = params[:type]
    if Rating.exists?("#{type}_id": params[:type_id], user_id: params[:rating_id])
      @new_rating = Rating.find_by("#{type}_id": params[:type_id], user_id: params[:rating_id])
    else
      @new_rating = {rating: 0}
    end
    render json: @new_rating.to_json
  end

  def rating_update
    if params[:type] === "venue"
      type = "venue"
    else
      type = "event"
    end

    @avg_rating = {average: Rating.where("#{type}_id": params[:rating_id]).average("rating").to_f.round(2), count: Rating.where("#{type}_id": params[:rating_id]).count}

    render json: @avg_rating.to_json

  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:rating, :user_id, :venue_id, :event_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def format average
    '%.2f' % average.to_f.round(2)
  end

  def show_rating ratings
    num = ratings.length.to_i
    if (num == 1)
      num.to_s + " Rating"
    else
      num.to_s + " Ratings"
    end
  end
end

app/views/ratings/_form.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- Setting 'default' rating depending on if user already has a rating -->

  <% if !@rating.rating.nil? %>
    <% default_rating = @rating.rating %>
  <% else %>
    <% default_rating = 0 %>
  <% end %>

  <div class="field">
    <%= f.hidden_field :rating, value: default_rating %>
  </div>

<!-- Passing through existing rating's ID -->
  <div class="field">
    <%= f.hidden_field :rating_id, value: rating.id %>
  </div>

<!-- Setting user_id as current user -->
  <% if !current_user.nil? %>
    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id  %>
    </div>
  <% end %>

  <% if !@venue.nil? %>
    <div class="field">
      <%= f.hidden_field :venue_id, value: @venue.id %>
    </div>
  <% end %>

  <% if !@event.nil? %>
    <div class="field">
      <%= f.hidden_field :event_id, value: @event.id  %>
    </div>
  <% end %>
<% end %>

app/views/ratings/_form_original.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %>
    <%= f.select :rating, [1, 2, 3, 4, 5], selected: @rating.rating %>
  </div>

  <% if !current_user.nil? %>
    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id  %>
    </div>
  <% end %>

  <% if !@venue.nil? %>
    <div class="field">
      <%= f.hidden_field :venue_id, value: @venue.id %>
    </div>
  <% end %>

  <% if !@event.nil? %>
    <div class="field">
      <%= f.hidden_field :event_id, value: @event.id  %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>User</th>
      <th>Venue</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.rating %></td>
        <td><%= rating.user %></td>
        <td><%= rating.venue %></td>
        <td><%= rating.event %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @rating.venue %>
</p>

<p>
  <strong>Event:</strong>
  <%= @rating.event %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>