config/routes.rb
Rails.application.routes.draw do

  get '/map_locations' => 'welcome#map_locations'
  get '/search' => 'welcome#search'
  resources :ratings do
    get 'get_rating'
    get 'rating_update'
  end

  get 'users/index'

  get 'users/show'

  post 'users/update'

  #generates /events/get_events route for calendar
  resources :events do
    get :get_events, on: :collection
  end

  resources :rsvps
  resources :event_reviews
  resources :venue_reviews
  resources :comments

  resources :events do
    get 'rating_update'
    get :add_featured
    get :remove_featured
  end
  resources :venues do
    # map locations for ...
    member do
      get 'map_location'
    end
    # Retrieve all map location for all venues
    # collection do
    #   get 'map_locations'
    # end
  end

  # Devise routes
  devise_for :users, path_prefix: 'my', controllers: { registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users

  root to: "welcome#index"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
class Venue < ApplicationRecord

  belongs_to :user
  validates :user, presence: true

  has_many :events
  has_many :venue_reviews

  has_many :ratings, :dependent => :delete_all

  has_many :comments

  validates :name, presence: true, uniqueness: true, length: { in: 5..20 }
  validates :description, presence: true, length: { in: 10..500 }

  resourcify

  #Adding Gmaps via geocoder
  geocoded_by :full_address
  after_validation :geocode

#Adding paperclip
  has_attached_file :image, styles: { small: "64x64#", med: "100x100#", large: "350x275#", xlarge: "400x400#" }, :default_url => "default_:style.png"
  validates_attachment :image,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }

    # instead of deleting, indicate the user requested a delete & timestamp it
    def soft_delete
      update_attribute(:deleted_at, Time.current)
    end

    # check if venue is active or has been soft deleted
    def active?
      !deleted_at
    end

private
  def full_address
    street_1.to_s + ' ' + street_2.to_s + ', ' + city.to_s + ', ' + state.to_s + ', ' + ', ' + zip.to_s
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  layout "index-show", only: [:show, :index]
  before_action :set_venue, only: [:show, :edit, :update, :destroy, :rate]

  load_and_authorize_resource
  skip_authorize_resource only: [:map_location]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/venues', :alert => exception.message
  end

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
    @ability = Ability.new(current_user)
  end

  def map_location
    @venue = Venue.find(params[:id])
    draw_map(@venue)
  end

  def map_locations
    venues = Venue.all # TODO
    draw_map(venues)
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    if @venue.active?
      @ability = Ability.new(current_user)
      @venue_review = VenueReview.new
      @venue_reviews = VenueReview.where(venue_id: @venue.id)

      @comment = Comment.new
      @comments = Comment.where(venue_id: @venue.id)

      # Finds user's current rating if existing or creates new blank rating. Also finds rating average
      rating = Rating.where(user: current_user, venue: @venue)
      if rating.length == 1
        @rating = rating[0]
      else
        @rating = Rating.new
      end
    else
      redirect_to '/venues'
    end
  end

  # def avg_rating(venue)
  #   if params[:venue_id].nil?
  #     @avg_rating = Rating.where(venue: venue).average("rating").to_f.round(2)
  #   else
  #     @avg_rating = Rating.where(venue_id: params[:venue_id]).average("rating").to_f.round(2)
  #   end
  # end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
    if !@venue.active?
      redirect_to '/venues'
    end
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    @ability = Ability.new(current_user)
    if !@ability.can(:manage, @venue, user_id: current_user.id)
      redirect_to 'venues'
    end
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @ability = Ability.new(current_user)
    if !@ability.can(:manage, @venue, user_id: current_user.id)
      redirect_to 'venues'
    end
    # For now, these are not needed, because we are doing soft deletes
    # @venue.ratings.delete_all
    # @venue.events.delete_all
    @venue.soft_delete
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def rate
    respond_to do |format|
      if @venue.update(rating: params[:rating])
        format.html { redirect_to @venue, notice: 'Rating was successfully submitted.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :description, :street_1, :street_2, :city, :state, :zip, :user_id, :image)
    end

    def draw_map(venues)
      @hash = Gmaps4rails.build_markers(venues) do |venue, marker|
        marker.lat(venue.latitude)
        marker.lng(venue.longitude)
        marker.infowindow('<a>' + venue.name + '</a>')
      end
      render json: @hash.to_json
    end

end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for @venue, html: { multipart: true } do |f| %>
  <% if venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 10  %>
  </div>

  <div class="form-group">
    <%= f.label :street_1 %>
    <%= f.text_field :street_1, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :street_2 %>
    <%= f.text_field :street_2, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip, class: "form-control" %>
  </div>

<br>

  <% ability = Ability.new(current_user) %>
  <% if ability.can?(:create, Venue) %>
    <div class="field">
      <input type="hidden" name="venue[user_id]" id="venue_id" value="<%=current_user.id%>">
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.file_field :image, class: "form-control"  %>
  </div>

  <br>

  <div class="actions form-group">
    <%= f.submit 'Submit Venue', class: "btn btn-success"  %>
  </div>
<% end %>
<br>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<div class="row">
  <div class="col-md-12" id="banner">
    <h1>Venues</h1>
  </div>
</div>

<div class="row">
  <% @venues.each do |venue| %>
    <% if venue.active? %>
      <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
          <a><%= image_tag(venue.image.url(:small)) %></a>
          <div class="caption">
            <h4><%= link_to "#{venue.name}", venue %></h4>
            <p><strong>Address:</strong><br>
            <%= "#{venue.street_1} #{venue.street_2} #{venue.city} #{venue.state} #{venue.zip}" %></p>
            <p><strong>Description:</strong><br><%= venue.description %></p>

            <div id="ratings">
              <p class="pull-right"><strong><%= show_rating venue.ratings %></strong></p>
              <p><strong>Avg Rating: <%= format venue.ratings.average("rating") %></strong></p>
            </div>
          </div>
          <p>
            <% if !current_user.nil? && venue.user == current_user %>
              <%= link_to 'Edit', edit_venue_path(venue) %> |
              <%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if !current_user.nil? && @ability.can?(:create, Venue) %>
    <div class="col-sm-4 col-lg-4 col-md-4">
        <h4><%= link_to 'New Venue', new_venue_path %></h4>
        <p>Do you know of a new or hidden dog paradise not listed here? Click the button below to spread the word!</p>
        <a class="btn btn-primary" href="/venues/new">Create New Venue</a>
    </div>
  <% end %>
</div>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<% content_for :head do %>
  <meta property="og:url"           content="https://barksandrec.herokuapp.com/venues/<%= venue_path(@venue) %>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="<%= @venue.name %>" />
  <meta property="og:description"   content="<%= @venue.description %>" />
  <meta property="og:image"         content="<%= @venue.image %>" />
<% end %>


<!-- Bootstrap Template -->
<div class="thumbnail">
  <div id="venue_map" data-venue-id="<%=@venue.id%>">
    Google Map will appear here...
  </div>

  <div class="caption-full">
    <div id="info-left">
      <div id="info-text">
        <p>
          <h3><%= @venue.name %></h3>
          <% if !current_user.nil? && @ability.can?(:rud, @venue, user_id: current_user.id) %>
            <%= link_to 'Edit', edit_venue_path(@venue) %> |
            <%= link_to 'Destroy', @venue, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>

        <p>
        <!-- Share/Tweet buttons for Facebook and Twitter -->
          <div class="fb-share-button" data-href="https://barksandrec.herokuapp.com/venues/<%= venue_path(@venue) %>" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A3000%2F&amp;src=sdkpreparse">Share</a></div>
          <a href="https://twitter.com/share/tweet?text=Bring%20your%20dogs%20to%20<%= @venue.name.gsub!(/\s/,'%20') %>%20as%20found%20on%20WhelpSD.com%21" class="twitter-share-button" data-show-count="false">Tweet</a>
        </p>

        <p>
          <strong>Address: </strong>
            <%= "#{@venue.street_1} #{@venue.street_2} #{@venue.city} #{@venue.state} #{@venue.zip}" %>
        </p>

        <p>
          <strong>Added By:</strong>
          <%= link_to "#{@venue.user.username}", "/users/#{@venue.user_id}"  %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @venue.description %>
        </p>

        <br>

        <!-- Ratings -->
        <div id="ratings">
          <%= render 'ratings/form', rating: @rating %>

          <% if !current_user.nil? && @ability.can?(:create, Rating) %>
            <p class="pull-left">
              <strong>My Rating:</strong>
              <span id="rating_span">
                <%= image_tag("star-off.png", id: "star_1") %>
                <%= image_tag("star-off.png", id: "star_2") %>
                <%= image_tag("star-off.png", id: "star_3") %>
                <%= image_tag("star-off.png", id: "star_4") %>
                <%= image_tag("star-off.png", id: "star_5") %>
              </span>
            </p>

          <% elsif current_user.nil? %>
            <p><%= link_to "Sign in to rate this venue!", new_user_session_path %></p>
          <% end %>

          <div class="rating_block">
            <span class="pull-left">
              <strong>Average Rating:&nbsp</strong>
              <span id="avg_rating"></span>
            </span>
            <span class="pull-right">
              <span id="count_rating">&nbspRatings</span>
            </span>
            </div> <!-- rating_block div -->
        </div> <!-- End Ratings -->

      </div> <!-- info-text -->
    </div> <!-- info-left -->

    <div id="info-right">
      <%= image_tag @venue.image.url(:large) %>
    </div>
  </div> <!-- class="caption-full" -->
</div> <!-- class="thumbnail" -->

<div class="five_space">
</div>

<p class="pull-right"><%= @comments.count %> Comment(s)</p>
<h3>Comments</h3>
<div class="well">
  <div>
    <!-- New comment form renders if user is logged in -->
    <!-- Also displays current user's rating of event -->
    <% if !current_user.nil? %>
      <h3>New Comment</h3>
      <%= render 'comments/form', comment: @comment %>
    <% else %>
     <%= link_to 'Sign in to Comment', new_user_session_path %>
    <% end %>
  </div>

  <hr>
  <% if @comments %>
    <% @comments.each do |comment| %>
      <div class="row">
        <div class="col-md-12">
          <h4> <%= comment.title %> </h4>
          <span>Posted By: <%= link_to "#{comment.user.username}", "/users/#{comment.user_id}" %> </span>
          <span class="pull-right"><%= "Posted " + date_to_s(comment.created_at) %></span>
          <p>
          <%= comment.text %>
          </p>
          <% if current_user == comment.user %>
            <%= link_to 'Edit', edit_comment_path(comment) %> |
            <%= link_to 'Destroy', comment_path(comment), method: "delete" %>
          <% end %>
        </div>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>